version: '3.8'
services:
  db:
    image: postgres:15
    container_name: db_refs
    command: -p 8888
    expose:
      - 8888
    env_file:
      - .env

  redis:
    image: redis:7
    container_name: redis_refs
    command: --port 5370
    expose:
      - 5370
    env_file:
      - .env

  app:
    build:
      context: .
    env_file:
      - .env
    container_name: fastapi_app_refs
    ports:
      - 8080:8080
    depends_on:
      - db
      - redis



